"""Add OFD Integration tables

Revision ID: 7624bf70ffc5
Revises: c7d350ee55a8
Create Date: 2026-01-31 09:02:26.724437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7624bf70ffc5'
down_revision: Union[str, Sequence[str], None] = 'c7d350ee55a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ofd_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ofd_providers_code'), 'ofd_providers', ['code'], unique=True)
    op.create_table('ofd_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('custom_base_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('first_import_date', sa.Date(), nullable=True),
    sa.Column('last_imported_date', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['ofd_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'provider_id', name='uq_business_provider')
    )
    op.create_table('product_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('ofd_product_id', sa.String(length=200), nullable=True),
    sa.Column('ofd_product_name', sa.String(length=500), nullable=False),
    sa.Column('tech_card_item_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['ofd_connections.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tech_card_item_id'], ['tech_card_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'ofd_product_id', 'ofd_product_name', name='uq_connection_product')
    )
    op.create_index('ix_product_mappings_tech_card_item_id', 'product_mappings', ['tech_card_item_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('ofd_receipt_id', sa.String(length=200), nullable=False),
    sa.Column('receipt_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiscal_document_number', sa.String(length=200), nullable=True),
    sa.Column('fiscal_sign', sa.String(length=200), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['ofd_connections.id'], ),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'ofd_receipt_id', name='uq_connection_receipt')
    )
    op.create_index('ix_sales_receipt_datetime_business', 'sales', ['receipt_datetime', 'business_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_mapping_id', sa.Integer(), nullable=True),
    sa.Column('tech_card_item_id', sa.Integer(), nullable=True),
    sa.Column('ofd_product_id', sa.String(length=200), nullable=True),
    sa.Column('ofd_product_name', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_mapped', sa.Boolean(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_mapping_id'], ['product_mappings.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tech_card_item_id'], ['tech_card_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_product_mapping_id', 'sale_items', ['product_mapping_id'], unique=False)
    op.create_index('ix_sale_items_sale_id', 'sale_items', ['sale_id'], unique=False)
    op.create_index('ix_sale_items_tech_card_item_id', 'sale_items', ['tech_card_item_id'], unique=False)
    op.create_table('sale_ingredient_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('tech_card_item_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], ),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.ForeignKeyConstraint(['tech_card_item_id'], ['tech_card_items.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_ingredient_expenses_category_created', 'sale_ingredient_expenses', ['category_id', 'created_at'], unique=False)
    op.create_index('ix_sale_ingredient_expenses_sale_item_id', 'sale_ingredient_expenses', ['sale_item_id'], unique=False)
    
    # Seed OFD providers
    op.execute("""
        INSERT INTO ofd_providers (code, name, base_url, is_active, description, created_at)
        VALUES 
            ('mock', 'Mock Provider', 'http://localhost:8000/mock', true, 'Для разработки и тестирования', NOW()),
            ('aqsi', 'AQSI', 'https://api.aqsi.ru', true, 'Реальный ОФД провайдер', NOW())
        ON CONFLICT (code) DO NOTHING;
    """)
    
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_column('businesses', 'tech_card_requires_approval')
    op.alter_column('expense_records', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('expense_records_created_by_fkey', 'expense_records', type_='foreignkey')
    op.create_foreign_key('expense_records_created_by_fkey', 'expense_records', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_ingredient_cost_category_date'), table_name='ingredient_cost_history')
    op.create_index(op.f('ix_ingredient_cost_history_id'), 'ingredient_cost_history', ['id'], unique=False)
    op.alter_column('invoices', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'users', ['created_by'], ['id'])
    op.drop_constraint(op.f('uq_starting_inventory_business_category_date'), 'starting_inventory', type_='unique')
    op.create_index(op.f('ix_starting_inventory_id'), 'starting_inventory', ['id'], unique=False)
    op.create_index(op.f('ix_tech_card_item_ingredients_id'), 'tech_card_item_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_tech_card_items_id'), 'tech_card_items', ['id'], unique=False)
    op.alter_column('user_businesses', 'role_in_business',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_businesses', 'role_in_business',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_tech_card_items_id'), table_name='tech_card_items')
    op.drop_index(op.f('ix_tech_card_item_ingredients_id'), table_name='tech_card_item_ingredients')
    op.drop_index(op.f('ix_starting_inventory_id'), table_name='starting_inventory')
    op.create_unique_constraint(op.f('uq_starting_inventory_business_category_date'), 'starting_inventory', ['business_id', 'category_id', 'inventory_date'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('invoices_created_by_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_created_by_fkey', 'invoices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('invoices', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ingredient_cost_history_id'), table_name='ingredient_cost_history')
    op.create_index(op.f('ix_ingredient_cost_category_date'), 'ingredient_cost_history', ['category_id', 'purchase_date'], unique=False)
    op.drop_constraint('expense_records_created_by_fkey', 'expense_records', type_='foreignkey')
    op.create_foreign_key('expense_records_created_by_fkey', 'expense_records', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('expense_records', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('businesses', sa.Column('tech_card_requires_approval', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.drop_index('ix_sale_ingredient_expenses_sale_item_id', table_name='sale_ingredient_expenses')
    op.drop_index('ix_sale_ingredient_expenses_category_created', table_name='sale_ingredient_expenses')
    op.drop_table('sale_ingredient_expenses')
    op.drop_index('ix_sale_items_tech_card_item_id', table_name='sale_items')
    op.drop_index('ix_sale_items_sale_id', table_name='sale_items')
    op.drop_index('ix_sale_items_product_mapping_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_sales_receipt_datetime_business', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_product_mappings_tech_card_item_id', table_name='product_mappings')
    op.drop_table('product_mappings')
    op.drop_table('ofd_connections')
    op.drop_index(op.f('ix_ofd_providers_code'), table_name='ofd_providers')
    op.drop_table('ofd_providers')
    # ### end Alembic commands ###
