"""add_business_and_user_business_tables

Revision ID: 841261b889ce
Revises: cf66b33dcf4f
Create Date: 2025-10-17 13:24:52.258341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '841261b889ce'
down_revision: Union[str, Sequence[str], None] = 'cf66b33dcf4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, fix NULL values before setting NOT NULL constraints
    op.execute("UPDATE permissions SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE permissions SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE role_permissions SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE role_permissions SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE role_permissions SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE user_permissions SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE user_permissions SET updated_at = NOW() WHERE updated_at IS NULL")
    op.execute("UPDATE user_permissions SET is_active = true WHERE is_active IS NULL")
    
    # Now set NOT NULL constraints
    op.alter_column('permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('role_permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('role_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
    # Create businesses table
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    
    # Create user_businesses table
    op.create_table('user_businesses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('role_in_business', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'business_id')
    )
    
    # Add business_id foreign key to user_permissions
    op.add_column('user_permissions', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_permissions', 'businesses', ['business_id'], ['id'])
    
    # Drop unique constraints on users table as they seem to be causing issues
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    
    # Drop business_id column from user_permissions
    op.drop_constraint('user_permissions_business_id_fkey', 'user_permissions', type_='foreignkey')
    op.drop_column('user_permissions', 'business_id')
    
    # Drop business tables
    op.drop_table('user_businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    
    op.alter_column('user_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('role_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('role_permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
