"""Add expense tracking tables: units, suppliers, periods, categories, invoices, records, balances

Revision ID: b8e3267f7084
Revises: ede8db2c1472
Create Date: 2025-10-18 14:48:58.351485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b8e3267f7084'
down_revision: Union[str, Sequence[str], None] = 'ede8db2c1472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - idempotent version."""
    # Get connection to check existing state
    conn = op.get_bind()
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('businesses', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    
    # Create units table (idempotent)
    result = conn.execute(sa.text("""
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_name='units'
    """))
    
    if result.fetchone() is None:
        op.create_table('units',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('symbol', sa.String(length=10), nullable=False),
            sa.Column('unit_type', sa.String(length=20), nullable=False),
            sa.Column('base_unit_id', sa.Integer(), nullable=True),
            sa.Column('conversion_factor', sa.Numeric(precision=10, scale=4), nullable=False, server_default='1.0'),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
            sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
            sa.PrimaryKeyConstraint('id'),
            sa.ForeignKeyConstraint(['base_unit_id'], ['units.id'], ondelete='CASCADE'),
        )
        op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop units table
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    
    op.alter_column('businesses', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('businesses', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
