"""Add expense tracking tables: units, suppliers, periods, categories, invoices, records, balances

Revision ID: b8e3267f7084
Revises: ede8db2c1472
Create Date: 2025-10-18 14:48:58.351485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e3267f7084'
down_revision: Union[str, Sequence[str], None] = 'ede8db2c1472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('businesses', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('businesses', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
